services:

  #   MARIADB   #
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - wordpress-network

  #   NGINX   #
  nginx:
    build: requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
      - adminer
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html/wordpress
      - portfolio:/var/www/html/portfolio
      # - adminer-volume:/var/www/html/adminer
    networks:
      - wordpress-network

  #   WORDPRESS   #
  wordpress:
    build: requirements/wordpress/
    depends_on:
      - mariadb
      - redis
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - wordpress-network

  #   ADMINER   #
  adminer:
    build: requirements/bonus/adminer/
    depends_on:
      - mariadb
    container_name: adminer
    restart: always
    networks:
      - wordpress-network

  #   REDIS   #
  redis:
    build: requirements/bonus/redis/
    container_name: redis
    restart: always
    env_file: .env
    networks:
      - wordpress-network

  #   FTP SERVER   #
  ftp_server:
    build: requirements/bonus/ftp_server/
    depends_on:
      - wordpress
    container_name: ftp_server
    restart: always
    env_file: .env
    volumes:
      - wordpress:/vsftpd
    ports:
      - 47400-47470:47400-47470
      - 21:21

  ssh-server:
    build: requirements/bonus/ssh-server/
    container_name: ssh-server
    restart: always
    ports:
      - 22:22

networks:
  wordpress-network:
    name: wordpress-network
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/ibaby/data/wordpress

  mysql:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/ibaby/data/mysql

  portfolio:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/ibaby/inception/srcs/requirements/bonus/portfolio/tools/

