version: "3"

services:
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    networks:
      - database

  wordpress:
    image: wordpress
    depends_on:
      - mariadb
    ports:
      - 3306:3306
      - 9000:9000
    networks:
      - database
      - server
    
  nginx:
    image: nginx
    depends_on:
      - mariadb
      - wordpress
    ports:
      - 9000:9000
      - 443:443
    networks:
      - server
