services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    env_file:
      - .env
    expose:
      - 3306
    volumes:
      - ./database:/var/lib/mysql
    networks:
      - wpnetwork

  nginx:
    image: nginx:1.15.12-alpine
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - 8080:80
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - wordpress:/var/www/html
    networks:
      - wpnetwork

  wordpress:
    depends_on:
      - mariadb
    build: requirements/wordpress/
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - wpnetwork

networks:
  wpnetwork:
    driver: bridge

volumes:
  wordpress: {}
