services:
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    env_file:
      - .env
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - wpnetwork

  nginx:
    build: requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - wpnetwork

  wordpress:
    build: requirements/wordpress/
    depends_on:
      - mariadb
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - wpnetwork

networks:
  wpnetwork:
    name: wpnetwork
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/ibaby/data/wordpress

  mysql:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/ibaby/data/mysql