services:
  mariadb:
    build: requirements/mariadb
    restart: always
    networks:
      - server
    # environment:
    #   - MYSQL_ROOT_PASSWORD=somewordpress
    #   - MYSQL_DATABASE=wordpress
    #   - MYSQL_USER=wordpress
    #   - MYSQL_PASSWORD=wordpress
    # ports:
    #   - 3306:3306
    # volumes:
    #   - db:/var/lib/databse

  wordpress:
    depends_on:
      - mariadb
    build: requirements/wordpress
    # environment:
    #   - WORDPRESS_DB_HOST=mariadb:3306
    #   - WORDPRESS_DB_USER=wordpress
    #   - WORDPRESS_DB_PASSWORD=wordpress
    #   - WORDPRESS_DB_NAME=wordpress
    networks:
      - server
    # ports:
      # - 3306:3306
      # - 9000:9000
      # - 8080:80
    
  nginx:
    build: requirements/nginx
    depends_on:
      - mariadb
      - wordpress
    # ports:
    #   - 9000:9000
    #   - 443:443
    networks:
      - server

networks:
  server:
    driver: bridge


# volumes:
#   db: {}