services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    env_file:
      - .env
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./database:/var/lib/mariadb
      - MYSQL_DATABASE=wordpress
    networks:
      - wpnetwork

  nginx:
    image: nginx:1.15.12-alpine
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - 8080:80
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - wordpress:/var/www/html
    networks:
      - wpnetwork

  wordpress:
    image: wordpress:5.1-fpm-alpine
    container_name: wordpress
    env_file: .env
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - wordpress:/var/www/html
    networks:
      - wpnetwork

networks:
  wpnetwork:
    driver: bridge

volumes:
  wordpress: {}
