services:
  mariadb:
    image: mariadb:v1
    build: requirements/mariadb/
    container_name: mariadb
    env_file:
      - .env
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - wpnetwork

  nginx:
    image: nginx:v1
    build: requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    networks:
      - wpnetwork

  wordpress:
    image: wordpress:v1
    build: requirements/wordpress/
    depends_on:
      - mariadb
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - wpnetwork

networks:
  wpnetwork:
    driver: bridge

volumes:
  wordpress:
    driver: local
  mysql:
    driver: local
