services:

  #   MARIADB   #
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - wordpress-network

  #   NGINX   #
  nginx:
    build: requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
      - adminer
    ports:
      - 443:443
    volumes:
      - adminer-volume:/var/www/html/adminer
      - wordpress:/var/www/html/wordpress
    networks:
      - wordpress-network

  #   WORDPRESS   #
  wordpress:
    build: requirements/wordpress/
    depends_on:
      - mariadb
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - wordpress-network

  #   ADMINER   #
  adminer:
    build: requirements/bonus/adminer/
    depends_on:
      - mariadb
    env_file: .env
    container_name: adminer
    restart: always
    volumes:
      - adminer-volume:/var/www/html/adminer
    networks:
      - wordpress-network

networks:
  wordpress-network:
    name: wordpress-network
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/ibaby/data/wordpress

  mysql:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/ibaby/data/mysql
  adminer-volume: {}