services:
  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    env_file:
      - .env
    # volumes:
    #   - /home/$USER/data/mysql:/var/lib/mysql
    networks:
      - wpnetwork

  nginx:
    image: nginx:1.15.12-alpine
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - 8080:80
    volumes:
      - /home/$USER/data/wordpress:/var/www/html
    networks:
      - wpnetwork

  wordpress:
    depends_on:
      - mariadb
    build: requirements/wordpress/
    container_name: wordpress
    env_file: .env
    volumes:
      - /home/$USER/data/wordpress:/var/www/html
    networks:
      - wpnetwork

networks:
  wpnetwork:
    driver: bridge

volumes:
  wordpress:
    driver: local
  mysql:
    driver: local
