version: '3'

services:
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: wordpress
    ports:
      - 8000:80

volumes:
  db_data: {}
